name: deploy to sever
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  build:


    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]


    steps:
      # 切换分支
      - name: Checkout
        uses: actions/checkout@main
      # 下载 git submodule
      # - uses: srt32/git-actions@v0.0.3
      #   with:
      #     args: git submodule update --init --recursive
      # 使用 node:10
      - name: use Node.js 16
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      # npm install
      - name: npm install and build
        run: |
          npm install
          npm run build
        env:
          CI: true
      # Deploy
      - name: Deploy
        uses: easingthemes/ssh-deploy@main
        env:
          SSH_PRIVATE_KEY: ${{ secrets.ACCESS_TOKEN }}
          ARGS: "-avz --delete"
          SOURCE: "dist/"
          REMOTE_PORT: ${{ secrets.REMOTE_PORT }}
          REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
          REMOTE_USER: ${{ secrets.REMOTE_USER }}
          TARGET: ${{ secrets.TARGET }}
          EXCLUDE: "api/,user/,team/,json/,pdf/"

